### ISSUE TITLE
Permission access for mix.gatling deploy

### ISSUE THREAD

**Issue by hafizio** [hashrocket/gatling#12]
I keep getting permission error when try to run `mix.gatling deploy <project.name>` in the server (Ubuntu 16.04).

Should I run the command using `sudo`?

**Comment by jrissler** [comment]
I'm running mix gatling.load {mix project name} - as my local user

and mix gatling.deploy {project_name} as sudo because of permissions around /etc/init.d and etc/nginx file creations, not sure if that's the best way but it felt right to me

**Comment by mrmicahcooper** [comment]
That's exactly right. It required `sudo` access. This happens automatically when you do git push. But if your'e running the deploy task manually, you'll have to `sudo`. I'll add that do the Readme.

**Comment by hafizio** [comment]
Thanks for the help!
