### ISSUE TITLE
Callbacks - Where exactly and what did I miss.

### ISSUE THREAD

**Issue by colindensem** [hashrocket/gatling#15]
Along with this comment really:
https://github.com/hashrocket/gatling/issues/8#issuecomment-253251182

Testing against a clean deploy and upgrade on DigialOcean > Ubuntu > root test vm., which works fine on the git push now :+1:  CentOs testing next after...

I wanted to complete the deployment loop with the callbacks to do npm/asset work as looking to mix in some elm magic before digest. This is 

Followed the documented notes on a `deploy.exs` and `upgrade.exs`. As soon as I add in the bash command, it errors on 
```
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 481 bytes | 0 bytes/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: ** (CompileError) /root/briskoda_hub/upgrade.exs:4: undefined function bash/3
remote:     (stdlib) lists.erl:1338: :lists.foreach/2
remote:     (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
remote: 
```

So `upgrade.exs` contains:
```
defmodule BriskodaHub.UpgradeCallbacks do

  def before_mix_digest(env) do
    bash("mkdir", ~w[-p priv/static], cd: env.build_dir) # optional: release may complain about this directory not existing
    bash("npm", ~w[install], cd: env.build_dir)
    bash("brunch", ~w[build --production], cd: env.build_dir)
    # bash("mix", ~w[phoenix.digest -o public/static], cd: env.build_dir)
    env
  end
end

```

**So I'm trying to figure this out without copying the bash features in**. I've currently only got this on the deploy server in the repository folder. so `/root/briskoda_hub/upgrade.exs`

_In the meantime, I'm posting this as the many eyes will be faster than my noggin to the blindingly obvious mistake I've made..._

Thanks for an awesome tool so far.

**Comment by jrissler** [comment]
@colindensem This is a bug I discovered and one that @mrmicahcooper is working to fix.

Its because the bash/3 + log/1 method doesn't exist in your app - here is what I did until the update makes it in: https://gist.github.com/jrissler/7e70cf1a738e2f4a0197db17cfd93b26

**Comment by colindensem** [comment]
I read the comment _slightly_ differently. I've done as you did in the gist in order to make progress though and I don't think it's that bad a step to have to do. 

The nice bash/3 is just that, a nice to have. The callbacks fire, so in that sense it's not a bug. If we can piggy back the gatling functions that would be an excellent bonus.

**Comment by mrmicahcooper** [comment]
@colindensem the goal is to be able to piggy back off the Gatling functions. I'll be working through this today to make sure it works properly.
The goal is for the client/deploying projects to have to do as little as possible. And not having to redefine those would be really nice. Thank you @colindensem  and @jrissler  for all the feedback. It's really great to have!

**Comment by mrmicahcooper** [comment]
The initial solution for this is to simply `import Gatling.Bash`.  I don't currently know how to quote the `deploy.exs` file, and inject the Gatling.Bash into it. But this should do the trick :)
