### ISSUE TITLE
Gatling task to delete a project deploy

### ISSUE THREAD

**Issue by loongmxbt** [hashrocket/gatling#23]
Request a Gatling task like `mix gatling.unload proj_name` to completely delete deploy.
Might include
1. Stopping the erlang node/process
2. Delete git folder and deployments/proj_name
3. Delete nginx conf
So, for testing, don't need to manually do these things.

**Comment by mrmicahcooper** [comment]
This is a great idea! I'd love to get this in there. Unfortunately, lately I've been in a shortage of free time. If you want to remove the everything about a deploy, here is a script I wrote up (it's untested but you should get the gist, hopefully):

APP=<project_name> && rm -rf ~/$(APP) && rm -rf ~/deployments/$(APP) && rm /etc/init.d/$(APP) && rm /etc/nginx/sites-enabled/$(APP) && rm /etc/init/nginx/sites-available/($APP)


Hope this helps!

**Comment by dennisreimann** [comment]
This is almost done, see 320354d260302669d3e9354f0826333889d4e5a4.

The only thing I couldn't get to work is running `mix ecto.drop` as this spawns a `Mix.Shell.IO.yes?` prompt. If someone knows a way how the prompt can be answered while the command is invoked by our `bash` function I'd love to integrate this too.

For now the unload task exits with a note about dropping the database manually.

**Comment by loongmxbt** [comment]
Thanks a lot @dennisreimann !  But I still have some problem.
I perform the following
```
 mix archive.install https://github.com/hashrocket/gatling_archives/raw/master/gatling.ez
```
to update gatling on server.

and `mix help`, `gatling.unload` is not in the list. And I perform unload task, seems not working.

```
mix gatling.unload ssst
** (Mix) The task "gatling.unload" could not be found. Did you mean "gatling.load"?
```

What's the right way to update gatling? What am I missing?

**Comment by dennisreimann** [comment]
This isn't in a release yet. You habe to install the archive straight from master of this repo - mix has an option for that as well :)

Let me know in case this does not work for you or you encounter problems with the unload task.
