### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by loongmxbt** [hashrocket/gatling#24]
Gatling is facinating! But following the docs will come up to some problems:

1. Server Prerequisites
git version must greater than 2.0
Install Node (using nvm)
Install Brunch gloabally, `npm install -g brunch`

2. Necessary Config Files
`./rel/config.exs`
`config/prod.secret.exs`
`domains`
`deploy.exs` -> deploy build static assets
`upgrade.exs` -> upgrade build static assets

3. How to setup SSL
Using Lets Encrypt

4. Trouble shooting

**Comment by loongmxbt** [comment]
When I follow the `deploy.exs` do something similar in `upgrade.exs`, something goes wrong.
```
defmodule Starsoul.UpgradeCallbacks do
  import Gatling.Bash

  def after_mix_digest(env) do
    bash("npm", ~w[install], cd: env.build_dir)
    bash("brunch", ~w[build --production], cd: env.build_dir)
    bash("mix", ~w[phoenix.digest -o public/static], cd: env.build_dir)
    env
  end

end
```

```
remote: $ mix phoenix.digest (/root/starsoul)
remote: Check your digested files at "priv/static"
remote: $ npm install (/root/starsoul)
remote: ** (ErlangError) erlang error: :enoent
remote:     (elixir) lib/system.ex:552: System.cmd("npm", ["install"], [stderr_to_stdout: true, into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}, cd: "/root/starsoul"])
```

**Comment by mrmicahcooper** [comment]
There are all great points @loongmxbt. 

If you're feeling up to it, perhaps you could make a pull request for the documentation you feel it's lacking?

Regarding item #4, Ideally, I'd like to support this out of the box and make this the default if you're running a Phoenix app. I think that would be awesome!

**Comment by loongmxbt** [comment]
Sure, I would very like to write some wiki for gatling!

**Comment by dennisreimann** [comment]
I'm currently also trying to improve the docs while making Gatling work for me :)

> Install Brunch gloabally, npm install -g brunch

You don't need to install modules globally as long as you run the commands via the npm wrapper: See this for my proposed change to the README: https://github.com/hashrocket/gatling/pull/30/commits/cc4006bbc80ce8e62edc44ac32cba38ca004fe7e#diff-04c6e90faac2675aa89e2176d2eec7d8R284

**Comment by dennisreimann** [comment]
> How to setup SSL. Using Lets Encrypt

As this can get pretty special, this should be done via a custom nginx.conf as proposed in #10 – nevertheless it could need some hints in the docs or example config. I'd be willing to help with this :)

**Comment by jrissler** [comment]
@dennisreimann I like the change in your compare

**Comment by dennisreimann** [comment]
I finally found the time to do a detailed writeup of the steps involved for my first deployment using Gatling: https://dennisreimann.de/articles/phoenix-deployment-gatling-ubuntu-digital-ocean.html

**Comment by loongmxbt** [comment]
@dennisreimann Great guide, helps a lot! Just some minor suggestions. 
1. explicitly tell include `{:distillery, "~> 1.0"}` in mix.exs as a compile-time dependency.
2. Some common problem trouble shooting, like if distillery raises error `One or more direct or transitive dependencies are missing from :applications or :included_applications, they will not be included in the release:`, add those dependencies into applications.

e.g. In order to use :ex_admin with distillery, I have to add :ex_admin, :exactor, :hound to applications.

**Comment by loongmxbt** [comment]
Here is a zh-cn translated guide. http://tatygrassini.github.io/

**Comment by dennisreimann** [comment]
Most of this is covered with the recent docs changes – I'll try to add another guide about customizing the nginx setup as this question also came up in #5.

**Comment by dennisreimann** [comment]
I have written the aforementioned guide and added it to the [Guides and Resources section in the README](https://github.com/hashrocket/gatling#guides-and-resources).

As the mentioned points are covered by now I am closing this one. Feel free to open another issue requesting more docs if something is unclear or missing! :)
