### ISSUE TITLE
Versioning individual environments

### ISSUE THREAD

**Issue by dchw** [hashrocket/gatling#26]
I like to have separate deploys of code for each environment - dev runs a newer version than test, which is newer than production. However, each server in my setup is semi-disposable, and I have a startup script that runs to bring each server to life. If possible, I really want this script to be able to push the correct version of the code, soGatling deploys the correct version.

Is there any plan (or are you open to) implementing some kind of environment/version correlation in Gatling? What I am picturing is something like this:

- Before doing anything of consequence, Gatling checks what version this server should be running. 
  - This should probably just be whatever the Mix env is set to.
  - The version corresponds to a particular tag in git.
- Gatling examines what version it is currently on. If it is the same, it does nothing. If its gone up, then it proceeds as it does now.

Why do I want to do this? It makes life easier, to me at least. All servers can have the same git commits pushed to them (I could perhaps even automate this) , and I can destroy and recreate the servers without any special handling. With this approach, I can get hot upgrades most of the time, _and_ easy re-creation for when that makes more sense.

Of course, i'm still new to Elixir deployment, so I could be totally off-base with what I am looking to do. I am willing to implement this if you think its a worthy endeavor.

**Comment by mrmicahcooper** [comment]
If I understand the question correctly, this should be possible currently. 

Check out this file to see how you can get `versions` based on your most the most recent commit on master: https://github.com/hashrocket/gatling/blob/master/mix.example.exs

With this on the project, you should just be able to do something like:

```
git push production <some_branch/tag>:master
```

And it should deploy that commit.

Hope this helps! Let me know how it works out!

**Comment by dchw** [comment]
I totally get that is possible, but I think there is some value that adding versioning could bring. 

1. It creates a source-controlled history of what version is where, and when it was there
2. You don't have to push the versions by hand, your servers can just detect the change, pull latest, and upgrade (or downgrade) if needed.
3. Less chance of pushing commits that "don't exist". In my workflow, I treat GitHub as the source of truth, and my local repo as suspect. If I can make everything derive from that (rather than whats on my dev box), i can feel more confident in my deployments.

Really, much of this comes from inherent laziness, and a worry that I might de-sync the repositories on the boxes with my app. Much easier to avoid issues if I can just keep the same repo on all of them.
