### ISSUE TITLE
Question about built_release_path default

### ISSUE THREAD

**Issue by dennisreimann** [hashrocket/gatling#29]
First off: Thanks for this project, it looks very promising!

I'm currently having trouble setting up everything as the `gatling.deploy` task fails when trying to `copy_release_to_deploy`. I am using a minimal Distillery config and haven't changed the [`output_dir`](https://hexdocs.pm/distillery/configuration.html#environment-release-settings).
Its default is `_build/<$MIX_ENV>/rel/<release_name>` and that's where my build is going when I invoke `gatling.deploy`.

However, the [`built_release_path` default](https://github.com/hashrocket/gatling/blob/master/lib/gatling/utilities.ex#L187) is in the `rel` directory (as opposed to `_build`) – this leads to the `copy_release_to_deploy` step failing, as it expects the build in `rel/...`

What am I doing wrong here? I think I could just add a Distillery config for that, but it doesn't seem like the proper way – that's why I'm asking. Thanks again!

**Comment by tmock12** [comment]
@dennisreimann I unfortunately don't have anything right now to test Gatling with, but looking at this commit https://github.com/bitwalker/distillery/commit/95c655ffaf083a71b7c904e12eadc3958586158b#diff-bed743e6a56afbb560284352b8e46a2d It appears Distillery has moved it to `_build` after this code was written in Gatling. 

PR's are definitely welcome if you have some spare time. If not, no worries. I've been wanting to test Gatling out anyways so I'm sure I can find some time later this week to whip up a dummy project and give it a run through. Thanks for opening this issue and bringing it to our attention. 👍

**Comment by dennisreimann** [comment]
@tmock12 thanks for replying! I'm using Gatling in my current project and can take care of testing it and sending you a pull request.

**Comment by colindensem** [comment]
As per the referenced dup, forgot to complete loop, the set output_dir is the way to go. Mainly as [built_release_path](https://github.com/hashrocket/gatling/blob/20dbb68653c2a07e33f7637e8557a7e43a440e5e/lib/gatling/utilities.ex#L187) Is hard setting it. If that changes then any existing will break; rock & hard place, with it, you have to add the config for output_dir.
ps @dennisreimann good deployment article :D

**Comment by dennisreimann** [comment]
@colindensem Thanks :) As Gatling uses Distillery I think it should build upon its defaults. Of course we could document setting the `output_dir` in th README, but imho it would be better to let it work out of the box and have as few adjustments as necessary – especially in this case where Gatling and Distillery are coupled.

As for the breaking change: That's unfortunate in the short term, however long term usability will profit from this I think and we should bump the version up to 1.1 then.

Any thoughts on that?

**Comment by colindensem** [comment]
Of course gatling should change to new defaults. It's part of being coupled to other projects after all.

I expect change for the long term benefit :+1:

**Comment by dennisreimann** [comment]
Alright, then I'll go ahead and send a PR with the necessary change(s) – thanks for the feedback!

**Comment by dennisreimann** [comment]
@tmock12 The pull request is done and can be reviewed :)
