### ISSUE TITLE
v1.1.0 breaks first-time deployment of new apps

### ISSUE THREAD

**Issue by IdahoEv** [hashrocket/gatling#40]
I've diagnosed at least part of the problems I'm having.  This commit is the culprit: https://github.com/hashrocket/gatling/commit/64b6d68109b0789d3e0be87365a55f5865547cac#diff-e6f9464d10bcc3e75cbf33de35289e38R50

This commit adds the creation of deploy_dir during "mix gatling.load". 
But the receive action checks for the presence of deploy_dir, and if the directory is present attempts an upgrade, as seen here:   https://github.com/hashrocket/gatling/blob/v1.1.0/lib/gatling/tasks/receive.ex#L17-L19

That upgrade action fails on first push because of course there is no previous release to upgrade.  You can see this in the console records I posted to #38.

This can be worked around just by `rm -rf /home/deploy/deployment` between `mix gatling.load <myapp>` and the initial push of the repository, which will allow the push to proceed normally and  allow `mix gatling.deploy` to succeed without error.    

I am closing #38 since this appears to be the root cause.  However, I still run in to #39 on subsequent updates, so I'll leave that ticket open.

**Comment by dennisreimann** [comment]
I will take a closer look at this as soon as I can. Thanks for your investigation!

**Comment by IdahoEv** [comment]
I think the proper solution is to have receive.ex not just check whether deploy_dir exists, but also 1) look for a previous fully deployed version inside that folder and 2) confirm that the app actually running.  That will keep it from trying to run a hot upgrade when there's no previous version to upgrade.

**Comment by dennisreimann** [comment]
The improved fix for this is in 0d32d42d6fa4b075162fb92708fb8376133d8e66
