### ISSUE TITLE
Move configuration files into a directory

### ISSUE THREAD

**Issue by aeons** [hashrocket/gatling#41]
The configuration files domains, deploy.exs and upgrade.exs should not be cluttering the root directory, in my opinion.

Maybe move them into `.gatling/` or `config/gatling/`?

This is just a suggestion, I like the project so far.

**Comment by dennisreimann** [comment]
Yep, this – like a lot of other ideas that come up recently - make total sense.

Unfortunately all of these things involve either keeping the code backwards compatible or breaking existing deployments. I currently try to shy away from moving too many things, but maybe it'd be better to tackle this sooner than later.
