### ISSUE TITLE
Missing .env file makes upgrade check fail

### ISSUE THREAD

**Issue by aeons** [hashrocket/gatling#43]
This line fails if the .env file does not exist: https://github.com/hashrocket/gatling/blob/e344f79b851f11f33cef95cf17f205bb9761af36/lib/gatling/init_script_template.sh.eex#L16

It's not clear what the format of the .env file is, and it is not created automatically.

Anyway, that line makes the init script print out a lot of output before the pong, making the upgrade test fail.

```
$ sudo service <app> ping
cat: /home/deploy/deployments/<app>/.env: No such file or directory
export HOME='/home/deploy/deployments/<app>'
export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'
export LC_ADDRESS=''
export LC_ALL='en_US.UTF-8'
export LC_COLLATE=''
export LC_CTYPE='UTF-8'
export LC_IDENTIFICATION=''
export LC_MEASUREMENT=''
export LC_MESSAGES=''
export LC_MONETARY=''
export LC_NAME=''
export LC_NUMERIC=''
export LC_PAPER=''
export LC_TELEPHONE=''
export LC_TIME=''
export MIX_ENV='prod'
export PATH='/home/deploy/.asdf/bin:/home/deploy/.asdf/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
export PORT='50425'
export PWD='/'
export TERM='screen'
pong
```

**Comment by aeons** [comment]
Even with that line removed, the update check does not seem to work:

```
$ git push production master
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 478 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: $ service <app> ping
remote: pong
remote: The app <app> is not deployed yet.
remote: Please invoke the initial deployment manually by running the following command:
remote:
remote: $ sudo --preserve-env mix gatling.deploy <app>
remote:
remote: In case you already deployed the app, make sure it is running so that an upgrade can be performed.
remote:
```

**Comment by dennisreimann** [comment]
The env file seems to be a feature that has been in the works but did not get finished yet, right @mrmicahcooper?

**Comment by aeons** [comment]
I found it now in the code.

I will try and commit a fix later.

**Comment by dennisreimann** [comment]
I want to get v1.1.1 out there to fix the deployment bugs introduced with v1.1.0 – after that we can tackle the proper integration of the env file, which would be nice to have imho.

**Comment by dennisreimann** [comment]
For me the current master@441e8653b58880c6b4fdb247ffaca94d2e5c2527 works when deploying and upgrading, can you confirm that @aeons?

**Comment by aeons** [comment]
It seems to work.

However, I found out where the $HOME variable is needed :)

```
$ sudo service <app> ping
erlexec: HOME must be set
```

**Comment by dennisreimann** [comment]
Thanks for your investigation! We'll leave it as it is, I don't want to evoke more turmoil :)
