### ISSUE TITLE
When is the git user setup?

### ISSUE THREAD

**Issue by Fahrradflucht** [hashrocket/gatling#6]
Following the README at the point where I'm told to `git remote add production git@<address.to.server>:<project_name>.git` where should this `git` user come from and why is the directory `.git`?

If I try to follow this guide that doesn't work at all. What works though (as you would expect) is using `git remote add production <username_user_before>@<address.to.server>:<project_name>`.

Am I missing something?

**Comment by mrmicahcooper** [comment]
Yes, the part you're missing is the `$ mix gatling.load {mix project name}`.

When you ssh into your server, your git user is simply what ever you're logged in as. So, if you ssh into an AWS instance, by default, the user is `ubuntu`. So the setup would look something like:

```
ssh ubuntu@xx.xx.xx.aws.com
mix gatling.load <project_name>
```

This will create a git repo called `<project_name>` on the remote server that you can push to with:

```
git push ubuntu@xx.xx.xx.aws.com:<project_name> master
```

I'll update the docs to make it more clear that your git path is your `<user>@<server>:<project_name>`

**Comment by Fahrradflucht** [comment]
Okay then I don't miss anything because that was what I did. I just found the docs irritating because the mentioned line made me think that `mix gatling.load` created an extra `git` user and a repo that ended in `.git` in it's home folder.

But then everything is fine 👍 , thanks.

**Comment by mrmicahcooper** [comment]
Great. Yes. That's an error in the docs. Thanks for the feedback!

**Comment by mrmicahcooper** [comment]
Reopening to keep track of the need to update docs :/

**Comment by mrmicahcooper** [comment]
I've added some elaboration on this fact in the README. Now I can close this. Thanks!
